"""add_status_to_tickets

Revision ID: 993ec7d7e206
Revises: c4b7082b2954
Create Date: 2026-06-01 14:30:06.307154

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "993ec7d7e206"
down_revision: str | Sequence[str] | None = "c4b7082b2954"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("idempotency_keys", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("idempotency_keys_idempotency_key_key"), type_="unique")
        batch_op.drop_index(batch_op.f("ix_idempotency_keys_idempotency_key"))
        batch_op.create_index(batch_op.f("ix_idempotency_keys_idempotency_key"), ["idempotency_key"], unique=True)
        batch_op.create_index(batch_op.f("ix_idempotency_keys_id"), ["id"], unique=False)

    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.String(), server_default="active", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.drop_column("status")

    with op.batch_alter_table("idempotency_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_idempotency_keys_id"))
        batch_op.drop_index(batch_op.f("ix_idempotency_keys_idempotency_key"))
        batch_op.create_index(batch_op.f("ix_idempotency_keys_idempotency_key"), ["idempotency_key"], unique=False)
        batch_op.create_unique_constraint(
            batch_op.f("idempotency_keys_idempotency_key_key"), ["idempotency_key"], postgresql_nulls_not_distinct=False
        )

    # ### end Alembic commands ###
